general.import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 14
offset = { y = 5 }

[window]
option_as_alt = "Both"
padding = {x = 0, y = 30}
decorations = "Transparent"
resize_increments = true
opacity = 0.8
blur = true
startup_mode = "Maximized"

[scrolling]
history = 50100
